version: '3.8'
services:
  zuppagood:
    expose:
      - "4000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - zuppagood
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount your Let's Encrypt certs (host must have run certbot)
      - /etc/letsencrypt/live/zpg.lat/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/zpg.lat/privkey.pem:/etc/ssl/private/privkey.pem:ro
    restart: unless-stopped
