version: '3.8'
services:
  ssr-app:
    image: registry.digitalocean.com/zuppagood-reg/zuppagood:latest
    expose:
      - "4000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - ssr-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount your Let's Encrypt certs (host must have run certbot)
      - /etc/letsencrypt/live/your.domain.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/your.domain.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    restart: unless-stopped
